### PR TITLE
Massive renovation, or: No Coffee, less Atom, more Raku

### PR DESCRIPTION
**Pull request by 2colours**
Hello,

Since this important repository [has been de-facto abandoned for years](https://github.com/Raku/atom-language-perl6/issues/90), I took up on it, familiarized with the content, started getting rid of Coffeescript... and perhaps went a bit further than I planned.

This PR is meant to indicate the start of a new era for this repository:
- Atom got discontinued. It might have always been a bad idea to make an official repo for one editor in particular. That has never been the important part. Therefore I think it's time to cut ties from the Atom legacy as much as possible. Maybe there can be a new repository for Pulsar but that should rather be "unofficial".
- The highlighting logic, using TextMate format, needs to be continued and improved, even. That's the best what we have for the time being, and it is tracked by a couple of third-party projects, like VSCode and GitHub's Linguist tool. This means the entry point needs to be kept low. Only the important content with preferably no custom technology, or reasonably straightforward, stable Raku, if necessary.

This PR is also big. I don't expect anyone to go through all changes, and given the state of things, I don't think that should be necessary. Feedback is welcome but all in all, I would like this to be merged AND also take control for the immediate future afterwards.

What I think is necessary in order for this to happen is to check the generated files. The CSON files produced by `dev/replace.sh` (and checked in under `grammars`) need to produce the very same JSON as `dev/generate-grammars.raku` does. I checked this using online converters and JSON differs but it would be good if someone could confirm that the content is right.  
If it is alright, I think, by all means, we can go forward from this.

### CODE REVIEW

**Comment by finanalyst** [comment]
@2colours this is an important start. But before merging, can we create a release from before the changes? I want to make sure there is a working highlighter available.

**Comment by finanalyst** [comment]
I have generated a release as v1.18.0  For some reason, the latest release seemed to have been v1.13.4, so initially I generated v1.15.0. But that was listed as exisiting.
Anyway v1.18.0 is a new tag, and has the most recent (Oct 2020) updates.

**Comment by 2colours** [comment]
> But before merging, can we create a release from before the changes? I want to make sure there is a working highlighter available.

@finanalyst I'm not sure what to do with this. Atom is dead, and I think soon it should go from the name of the repository for good. Going forward, "the highlighter" is merely the set of files generated inside the `grammars` folder. In this sense, I'm not sure if there is much point in talking about versions or releases. Where would it be released, if it's really just a bunch of data in TextMate editor format as JSON?

**Comment by 2colours** [comment]
@samcv @JJ in case you are interested, I'd be curious about your feedback.

**Comment by JJ** [comment]
After reading the introduction, I kinda understand what this PR is not, but I don't really get what it *is*. A few files into it I bump into "benchmark.js", with no top comments or explanation, so I got really lost.
This goes to say that I don't think I'm qualified to understand and thus approve it. If you think it's OK, go ahead with it. And thanks for the work done.

**Comment by 2colours** [comment]
Well, first of all, thank you for the reminder: some changes in the CONTRIBUTING file were "dangling", added them now. It's hard to refer to something you haven't actually uploaded...

To be frank, that's a bit disappointing if all you understood from the changes and the description together "what it isn't and not what it is". 😅 It kinda itches me to know what it isn't...

Okay, I kinda know what it isn't and that might tell you what it is: it isn't about semantic changes. In fact, it shouldn't have any changes in the behavior. There is a benchmark.js with no top comments or explanation - because there was a benchmark.coffee with no top comments or explanation. I am as clueless about it as you are. My promise/responsibility is that _it should do the exact same thing that it used to, except with technology somebody has a chance to be familiar with in 2023_.

This goes for the whole thing. I don't know why the CSON files had the content that they did - my promise is that you can run the only actual script under dev/ (and now actually read what it does, in `CONTRIBUTING.md` - yay!), and get equivalent JSON content to the old CSON files. No more dependency on CSON, no more template-ish hacking and intermediate files; it's all structured Raku content.

**Comment by JJ** [comment]
> Well, first of all, thank you for the reminder: some changes in the CONTRIBUTING file were "dangling", added them now. It's hard to refer to something you haven't actually uploaded...
> 

OK, let's see if that clarifies things...

> To be frank, that's a bit disappointing if all you understood from the changes and the description together "what it isn't and not what it is". sweat_smile It kinda itches me to know what it isn't...

Well, to be honest I didn't understand what the scope of the PR is, which makes it difficult to say something meaningful. I trust you have done the right thing, but as stated above, it's not entirely clear for me where you want to arrive. I kinda got the idea this repository is going to no longer be about Atom, but more about a general syntax highlighting thingie?
> 
> Okay, I kinda know what it isn't and that might tell you what it is: it isn't about semantic changes. In fact, it shouldn't have any changes in the behavior. There is a benchmark.js with no top comments or explanation - because there was a benchmark.coffee with no top comments or explanation. I am as clueless about it as you are. My promise/responsibility is that _it should do the exact same thing that it used to, except with technology somebody has a chance to be familiar with in 2023_.
> 

It would help to clearly indicate the scope of the PR. There are changes in JS files, in markdown, some files have been deleted, some added.  I trust you have done the right thing, but you've requested feedback from me, and I need a bit more info to be able to give it. If you have translated the benchmark to JS without understanding what it does, wouldn't it be better to just eliminate it?

> This goes for the whole thing. I don't know why the CSON files had the content that they did - my promise is that you can run the only actual script under dev/ (and now actually read what it does, in `CONTRIBUTING.md` - yay!), and get equivalent JSON content to the old CSON files. No more dependency on CSON, no more template-ish hacking and intermediate files; it's all structured Raku content.

But it would help to know what the Raku content is *for*. Again, scope is everything, even more so in a big PR. If you want help, help us understand what's what here and we'll do our best...

**Comment by 2colours** [comment]
> I kinda got the idea this repository is going to no longer be about Atom, but more about a general syntax highlighting thingie?

Yes, that's definitely a plan of mine. However, as of this PR, I didn't deliberately "mess up" anything Atom-related. The supposedly important changes were around the data format and generation.

> There are changes in JS files

No, there aren't; Coffeescript files _have been replaced_ by equivalent JS files.

> If you have translated the benchmark to JS without understanding what it does, wouldn't it be better to just eliminate it?

I don't know but I definitely didn't want to further complicate things by doing decisions like that. I think that decision actually takes more effort than to replace the file with an equivalent JS.

> But it would help to know what the Raku content is for. Again, scope is everything, even more so in a big PR. If you want help, help us understand what's what here and we'll do our best...

In all honesty, I don't think I am the right person to ask. I started from what you can see, without any guidance, and got to what you can see. I don't know more about textmate JSON's than what you can gather from this repository. On the other hand, the fact that the Raku script takes the Raku hashes and generates the JSON files from them, is actually written down (that's what I commited last). Supposedly I didn't add and didn't take away. Once I know more, I will add more. If you don't know what it's about, please ignore my ping; I just assumed/hoped that you would.

**Comment by 2colours** [comment]
Due to lack of feedback, I decided to proceed with the changes.

**Pull request merged**
